### PR TITLE
don't panic on polygon with >4 verts

### PR DESCRIPTION
**Pull request by astraw**
As this changes the public API, the version will have to be
bumped.

### CODE REVIEW

**Review by kvark — APPROVED** [review]
Thank you!
How do you feel about landing this in a non-breaking way? I.e. we could add a method like `try_new` that has default implementation (via `new`) and can be used in `parse_face`. This way, I think, it's no longer a breaking change.

**Comment by astraw** [comment]
Yes, good suggestion. I updated my PR.

**Review by kvark — APPROVED** [review]
bors r+

**Comment by astraw** [comment]
Thanks - I noticed the new release already. That makes life easier for me - thanks also for that!

**Pull request merged**
